name: Phoenix Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Check NDK
        run: |
          echo "NDK installed successfully"

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: .
